std                =require("std")
-- package.path      = "./lua/?.lua;" .. package.path
reverse_pro        =require("processor/reverse_pro")
select_char        =require("processor/select_char")
quick_warp         =require("processor/quick_warp")
plain_return       =require("processor/plain_return")
smart_punct        =require("processor/smart_punct")
module_cn_en       =require("translator/module_cn_en")
module_dmma        =require("translator/module_dmma")
module_dmma_upper  =require("translator/module_dmma_upper")
module_fnua_cn     =require("translator/module_fnua_cn")
module_fnua_triple =require("translator/module_fnua_triple")
save_entry         =require("translator/save_entry")
chinese_number     =require("translator/chinese_number")
unicode            =require("translator/unicode")
execute            =require("translator/execute")
custom_symbol      =require("translator/custom_symbol")
custom_time        =require("translator/custom_time")
ts_cn              =require("translator/ts_fixed").new({syllableLength=2})
ts_cn_quanpin      =require("translator/ts_cn_quanpin")
ts_triple          =require("translator/ts_fixed").new({syllableLength=3})
ts_en              =require("translator/ts_en")
fil_Uniquifier     =require("filter/Uniquifier")
fil_KijinSeija     =require("filter/KijinSeija")
fil_Unicode        =require("filter/Unicode")
recorder           =require("other/recorder")
local Utils <const> = require("utils")
init               ={}
function init.init(env)
 Utils.keyMapInitialize(env)
end
function init.func()
 return 2
end
ts_fanganlianxi_p,
ts_fanganlianxi_t=table.unpack((require("mixed/ts_fanganlianxi")))
