local keymaps=require("hoofcushion.keymaps")
local switchers=require("hoofcushion.switchers")
local schema=std.extend(
 require("hoofcushion.schema.base"),
 require("hoofcushion.schema.hans"),
 require("hoofcushion.speller.fixed.triple"),
 {
  schema={
   schema_id="ts_cn_triple",
   name="三码拼音",
   description=[[
汉语输入方案之三码拼音
原作者为阿森纳里
由 Hoofcushion 改进适配 Qwerty 布局
]],
  },
  engine={
   translators={
    "lua_translator@*ts_fixed*translator@translator",
   },
  },
  translator={
   initial_quality=1,
   dictionary="ts_cn_terra",
   prism="ts_cn_triple",
   user_dict="ts_cn_triple",
   syllable_len=3,
  },
 },
 {
  key_binder={
   bindings={
    keymaps.ascii_punct,
    keymaps.full_shape,
    keymaps.filter_simplification,
    keymaps.filter_emoji,
    keymaps.filter_zhuyin,
    keymaps.filter_decensor,
    keymaps.filter_symbol,
    keymaps.filter_trans,
    keymaps.filter_Unicode,
    keymaps.filter_Reverse,
   },
  },
  switches={
   switchers.ascii_mode,
   switchers.ascii_punct,
   switchers.full_shape,
   switchers.filter_simplification,
   switchers.filter_emoji,
   switchers.filter_symbol,
   switchers.filter_zhuyin,
   switchers.filter_decensor,
   switchers.filter_trans,
   switchers.filter_Unicode,
   switchers.filter_Reverse,
  },
 },
 {
  filter_simplification={
   opencc_config="t2s.json",
  },
 },
 --- English
 {
  schema={
   dependencies={
    "ts_en",
   },
  },
  engine={
   translators={
    "lua_translator@*ts_en*translator@module_en",
   },
  },
  abc_segmentor={
   extra_tags={"english"},
  },
  module_en=std.extend(
   require("hoofcushion.schema.english").translator,
   {tag="english"}
  ),
 },
 {
  schema={
   dependencies={
    "module_fnua_triple",
   },
  },
  engine={
   segmentors=function(self)
    std.tbl.insert_at(self,"affix_segmentor@module_fnua_triple","matcher",1)
   end,
   processors=function(self)
    std.tbl.insert_at(self,"lua_processor@*reverse_pro*processor@module_fnua_triple","recognizer",1)
   end,
   translators={
    "lua_translator@*ts_cn_triple.fnua@module_fnua_triple",
   },
  },
  module_fnua_triple={
   prefix="`",
   trigger="space",
   tag="module_fnua_triple",
   tips="〔拼音反查〕",
   dictionary="module_fnua_triple",
   spelling_hints=99,
   enable_user_dict=false,
  },
  recognizer={
   patterns={
    module_fnua_triple="`.*$",
   },
  },
 }
)
return schema
