local keymaps=require("hoofcushion.keymaps")
local switchers=require("hoofcushion.switchers")
local schema=std.extend(
 require("hoofcushion.schema.base"),
 require("hoofcushion.schema.hans"),
 require("hoofcushion.speller.quanpin"),
 {
  schema={
   schema_id="ts_cn_quanpin",
   name="全拼",
   description=[[
汉语输入方案之全拼
词库基于雾凇拼音 (https://github.com/iDvel/rime-ice)
]],
  },
  engine={
   translators={
    "lua_translator@*ts_cn_quanpin*translator@translator",
   },
  },
  translator={
   initial_quality=1,
   dictionary="ts_cn_quanpin",
   user_dict="ts_cn_quanpin",
   prism="ts_cn_quanpin",
  },
 },
 {
  key_binder={
   bindings={
    keymaps.ascii_punct,
    keymaps.full_shape,
    keymaps.filter_simplification,
    keymaps.filter_emoji,
    keymaps.filter_zhuyin,
    keymaps.filter_decensor,
    keymaps.filter_symbol,
    keymaps.filter_trans,
    keymaps.filter_Unicode,
    keymaps.filter_Reverse,
   },
  },
  switches={
   switchers.ascii_mode,
   switchers.ascii_punct,
   switchers.full_shape,
   switchers.filter_simplification,
   switchers.filter_emoji,
   switchers.filter_symbol,
   switchers.filter_zhuyin,
   switchers.filter_decensor,
   switchers.filter_trans,
   switchers.filter_Unicode,
   switchers.filter_Reverse,
  },
 },
 {
  filter_simplification={
   opencc_config="s2t.json",
  },
 },
 --- English
 {
  schema={
   dependencies={
    "ts_en",
   },
  },
  engine={
   translators={
    "lua_translator@*ts_en*translator@module_en",
   },
  },
  abc_segmentor={
   extra_tags={"english"},
  },
  module_en=std.extend(
   require("hoofcushion.schema.english").translator,
   {tag="english"}
  ),
 },
 --- Cn-En mixed
 {
  schema={
   dependencies={
    "module_cn_en_quanpin",
   },
  },
  engine={
   translators={
    "script_translator@module_cn_en_quanpin",
   },
  },
  module_cn_en_quanpin={
   initial_quality=1,
   dictionary="module_cn_en",
  },
 }
)
return schema
