local keymaps=require("hoofcushion.keymaps")
local switchers=require("hoofcushion.switchers")
local schema=std.extend(
 require("hoofcushion.schema.base"),
 require("hoofcushion.schema.hans"),
 require("hoofcushion.speller.quanpin"),
 {
  schema={
   schema_id=NS.ts_cn_quanpin,
   name="全拼",
   description=[[
汉语输入方案之全拼
词库基于雾凇拼音 (https://github.com/iDvel/rime-ice)
]],
  },
  engine={
   translators={
    {
     name="lua_translator@translator",
     module=require("ts_cn_quanpin").translator,
     option={
      initial_quality=1,
      dictionary=NS.ts_cn_quanpin,
      user_dict=NS.ts_cn_quanpin,
      prism=NS.ts_cn_quanpin,
     },
    },
   },
  },
 },
 {
  key_binder={
   bindings={
    keymaps.ascii_punct,
    keymaps.full_shape,
    keymaps.filter_simplification,
    keymaps.filter_emoji,
    keymaps.filter_zhuyin,
    keymaps.filter_decensor,
    keymaps.filter_symbol,
    keymaps.filter_trans,
    keymaps.filter_Unicode,
    keymaps.filter_Reverse,
   },
  },
  switches={
   switchers.ascii_mode,
   switchers.ascii_punct,
   switchers.full_shape,
   switchers.filter_simplification,
   switchers.filter_emoji,
   switchers.filter_symbol,
   switchers.filter_zhuyin,
   switchers.filter_decensor,
   switchers.filter_trans,
   switchers.filter_Unicode,
   switchers.filter_Reverse,
  },
 },
 {
  filter_simplification={
   opencc_config="s2t.json",
  },
 },
 --- English
 {
  schema={
   dependencies={
    NS.ts_en,
   },
  },
  engine={
   translators={
    {
     name="lua_translator@module_en",
     module=require("ts_en").translator,
     option=std.extend(
      LuaSchema.new(require("hoofcushion.schema.english")).info.translator,
      {tag="english"}
     ),
    },
   },
  },
  abc_segmentor={
   extra_tags={"english"},
  },
 },
 --- Cn-En mixed
 {
  schema={
   dependencies={
    "module_cn_en_quanpin",
   },
  },
  engine={
   translators={
    {
     name="script_translator@module_cn_en_quanpin",
     option={
      initial_quality=1,
      dictionary="module_cn_en",
     },
    },
   },
  },
 }
)
return schema
