
local keymaps=require("hoofcushion.keymaps")
local switchers=require("hoofcushion.switchers")
local schema=rime.extend(
 require("hoofcushion.schema.base"),
 require("hoofcushion.speller.fixed.hoofcushion"),
 {
  schema={
   schema_id="ts_cn_double",
   name="定长拼音",
   description=[[
汉语输入方案之定长
词库基于雾凇拼音 (https://github.com/iDvel/rime-ice)
]],
  },
  engine={
   translators={
    {
     name="lua_translator@*ts_fixed*translator@translator",
     option={
      initial_quality=1,
      dictionary="ts_cn_quanpin",
      user_dict="ts_cn_double",
      prism="ts_cn_double",
      syllable_len=2,
     },
    },
    "lua_translator@*user-dict-blocker*length@1",
    --- Cn-En mixed
    {
     name="script_translator@module_cn_en_double",
     option={
      initial_quality=1,
      dictionary="module_cn_en_quanpin",
      prism="module_cn_en_double",
     },
     dependencies={
      "module_cn_en_double",
     },
    },
   },
  },
 },
 {
  key_binder={
   bindings={
    keymaps.ascii_punct,
    keymaps.full_shape,
    keymaps.filter_simplification,
    keymaps.filter_emoji,
    keymaps.filter_zhuyin,
    keymaps.filter_huoxin,
    keymaps.filter_symbol,
    keymaps.filter_trans,
    keymaps.filter_Unicode,
    keymaps.filter_Reverse,
   },
  },
  switches={
   switchers.ascii_mode,
   switchers.ascii_punct,
   switchers.full_shape,
   switchers.filter_simplification,
   switchers.filter_emoji,
   switchers.filter_symbol,
   switchers.filter_zhuyin,
   switchers.filter_huoxin,
   switchers.filter_trans,
   switchers.filter_Unicode,
   switchers.filter_Reverse,
  },
 },
 {
  filter_simplification={
   opencc_config="s2t.json",
  },
 },
 --- English
 {
  schema={
   dependencies={
    "ts_en",
   },
  },
  engine={
   translators={
    "lua_translator@*ts_en*translator@module_en",
   },
  },
  abc_segmentor={
   extra_tags={"english"},
  },
  module_en=rime.extend(
   require("hoofcushion.schema.english").translator,
   {tag="english"}
  ),
 },
 --- Reverse lookup
 {
  schema={
   dependencies={
    "module_fnua_cn",
   },
  },
  engine={
   segmentors=function(self)
    rime.tbl.insert_at(self,"affix_segmentor@module_fnua_cn","matcher",1)
   end,
   processors=function(self)
    rime.tbl.insert_at(self,"lua_processor@*reverse_pro*processor@module_fnua_cn","recognizer",1)
   end,
   translators={
    "lua_translator@*ts_cn_double.fnua@module_fnua_cn",
   },
  },
  module_fnua_cn={
   prefix="`",
   trigger="space",
   tag="module_fnua_cn",
   tips="〔拼音反查〕",
   dictionary="module_fnua_cn",
   spelling_hints=99,
   enable_user_dict=false,
  },
  recognizer={
   patterns={
    module_fnua_cn="`.*$",
   },
  },
 }
)
return schema
