return {
 target="default",
 patch={
  menu={
   page_size=6,
  },
  schema_list={
   {schema=NS.ts_cn_double},
   {schema=NS.ts_cn_quanpin},
   {schema=NS.ts_cn_triple},
   {schema=NS.ts_en},
  },
  switcher={
   abbreviate_options=true,
   caption="方案选单",
   fold_options=true,
   hotkeys={
    "Control+grave",
    "Control+backslash",
   },
   save_options={
    NS.ascii_punct,
    NS.full_shape,
    NS.filter_s2t,
    NS.filter_emoji,
    NS.filter_symbol,
   },
   option_list_separator="/",
  },
 },
}
