return {
 target="default",
 patch={
  menu={
   page_size=6,
  },
  schema_list={
   {schema="ts_cn_double"},
   {schema="ts_cn_quanpin"},
   {schema="ts_cn_triple"},
   {schema="ts_en"},
  },
  switcher={
   abbreviate_options=true,
   caption="〔方案选单〕",
   fold_options=true,
   hotkeys={
    "Control+grave",
    "Control+backslash",
   },
   save_options={
    "ascii_punct",
    "full_shape",
    "filter_s2t",
    "filter_emoji",
    "filter_symbol",
   },
   option_list_separator="／",
  },
 },
}
