local utils=require("utils")
local schema=utils.tbl_extend(
 require("hoofcushion.ts_detail"),
 require("hoofcushion.speller.double.chaos_20"),
 require("hoofcushion.schema_settings.ts_cn"),
 function(schema)
  table.insert(schema.engine.segmentors,3,"affix_segmentor@module_fnua_cn")
  table.insert(schema.engine.processors,2,"lua_processor@*reverse_pro*processor@module_fnua_cn")
 end,
 {
  schema={
   schema_id="ts_cn",
   name="双拼",
   [[
汉语输入方案之双拼
词库基于雾凇拼音 (https://github.com/iDvel/rime-ice)
]],
   dependencies={
    "ts_en",
    "module_cn_en",
    "module_fnua_cn",
   },
  },
  engine={
   translators={
    "lua_translator@module_fnua_cn",
    "lua_translator@*ts_fixed*translator@translator",
    "lua_translator@*ts_en*translator@module_en",
    "script_translator@module_cn_en",
   },
  },
  abc_segmentor={
   extra_tags={"ts_en"},
  },
  translator={
   initial_quality=1,
   dictionary="ts_cn",
   user_dict="ts_cn_double",
   prism="ts_cn_double",
   syllable_len=2,
  },
  module_cn_en={
   initial_quality=1,
   dictionary="module_cn_en",
   user_dict="module_cn_en",
  },
  module_en=utils.tbl_extend(
   require("hoofcushion.ts_en").translator,
   {tag="ts_en"}
  ),
  module_fnua_cn={
   prefix="`",
   trigger="space",
   tag="module_fnua_cn",
   tips="〔拼音反查〕",
   dictionary="module_fnua_cn",
   spelling_hints=99,
   enable_user_dict=false,
  },
  recognizer={
   patterns={
    module_fnua_cn="`[^0-9]*$",
   },
  },
 }
)
return schema
